### ISSUE TITLE
Infinite Loading Spinner

### ISSUE THREAD

**Issue by eternal-joel** [imfunniee/fimbo#3]
Hello, the files were downloaded with the titles:

- index.js
- index.css
- index.html

In order to maintain organized, I have changed the name of the files. I have edited the code that states what the new file name of the style sheet is and I only see the spinner when reloading the page and the page never loads. Is there something that I am doing wrong?

**Comment by eternal-joel** [comment]
@imfunniee

**Comment by imfunniee** [comment]
where are the files? 👀

**Comment by eternal-joel** [comment]
The files are in one folder, located on my local hard drive.

**Comment by imfunniee** [comment]
@eternal-joel are the files in a repo so I can take a look at them and point out the specific bug?

> I am just wondering if there is a command prohibiting me from changing the name of the files.

nah, these are just static html files.

**Comment by imfunniee** [comment]
unactive. closed.
